data:
  raw: "./Data/" 
  prr: "./Data/Output-PRR/"
  wafer_map_raw: "./Data/Wafer-Map/"
  wafer_map_png: "./Data/WaferMap_PNG/"
  wafer_map_resized: "./Data/Wafer-Map_resized/"
  wafer_map_grayscale: "./Data/Wafer-Map_grayscale/"
  real: "./Data/Wafer-Map_grayscale/"
  test: "./Output/"
  zip: "./Data/Zipfile-STDF/"
  kaggle_png: "./Data/Kaggle_PNG/" 
  npz_dataset: "./Data/Wafer_Map_Datasets.npz" 
  auto_labeled: "Data/AutoLabeled"

output:
  checkpoints: "./Output/checkpoints/"
  predictions: "./Output/predictions/"
  logs: "./Output/logs/"

model:
  name: "EfficientNetB0"
  epochs: 1
  batch_size: 32
  freeze_backbone: true

training:
  train_subset: 2000
  val_subset: 500
  test_images_per_label: 100