data:
  raw: "./Data/" #for.npz,.pkl file
  prr: "./Data/Output-PRR/" # ข้อมูล PRR 
  wafer_map_raw: "./Data/Wafer-Map/"
  wafer_map_png: "./Data/WaferMap_PNG/"        # มีโฟลเดอร์ label ย่อยๆ
  wafer_map_resized: "./Data/Wafer-Map_resized/"
  real: "./Data/WaferMap_PNG/"
  test: "./Output/" 
  zip: "./Data/Zipfile-STDF/"

output:
  checkpoints: "./Output/checkpoints/"
  predictions: "./Output/predictions/"
  logs: "./Output/logs/"

model:
  name: "EfficientNetB0"
  epochs: 5
  batch_size: 32
  freeze_backbone: true

training:
  train_subset: 2000
  val_subset: 500
  test_images_per_label: 100